Added 255 kOhm Resistor
hytech-racing/circuits-support-2022 pull request #22
Opened 2021-08-20 19:50 UTC by ckaminsky7

# Pull Request (PR) into Circuits-Support-2022

## Part Description
Added a Panasonic Electronic Company 255 kOhm resistor.

## Additional Information

## Checklist
- [ ] Did you create any new schematics or boards?
- - [ ] Did you *make a PR* for them in `circuits-2022`? If so, please pause until you get this PR merged.
- [ ] Did you pull `main` into your branch?
- - [ ] Did you *check for merge conflicts*?
- - [ ] Did you *resolve* any that occurred? ***If you are having trouble or are confused, contact a lead!***
- [ ] Did you fill out the above template?
- [ ] Did you assign the right people for review (on the right)?
- [ ] Did you comply with the library style guidelines?

2021-08-22 21:39 UTC, Arvind-Srinivasan requested changes
Did you set them as constant attributes?

2021-08-22 22:21 UTC, 19etweinstock commented
manufacturer is wrong

2021-08-29 18:57 UTC, 19etweinstock approved these changes

2021-08-29 18:57 UTC, 19etweinstock approved these changes

2021-08-29 18:58 UTC, merged